name: Test

on:
  push
  
jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-latest, windows-latest] # likely windows-latest is enough
          python-version:  # library combinations can be written here too!
            - "3.9"
            - "3.10"
            - "3.11-dev"
    name: Testing
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # internal action to checkout the code

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
