#name: Test
#
#on:
#  push
#
#
#jobs:
#  run-tests:
#    strategy:
#      fail-fast: false
#      matrix:
#          os: [ubuntu-latest, windows-latest] # likely windows-latest is enough
#          python-version:  # library combinations can be written here too!
#            - "3.9"
#            - "3.10"
#            - "3.11-dev"
#    name: Testing
#    runs-on: ${{ matrix.os }}
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3  # internal action to checkout the code
#
#      - name: Set up Python ${{ matrix.python-version }}
#        uses: actions/setup-python@v4
#        with:
#          python-version: ${{ matrix.python-version }}
#
#      - name: Install dependencies
#        run: |
#          conda install -c conda-forge --file requirements.txt
#
#      - name: Run tests
#        run: pytest


name: Use Setup-Miniconda From Marketplace
on: [push]

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest", "windows-latest"]
            python-version: # library combinations can be written here too!
              - "3.9"
              - "3.10"
              - "3.11-dev"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: Run pytest
        shell: bash -l {0}
        run: |
            conda install pytest
            pytest